version: "3.9"

services:
  portainer-nginx:
    image: nginx:1.23.2
    ports:
      - "9000:9000"
    container_name: portainer-nginx
    networks:
      - portainer-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./portainer_certificado:/etc/nginx/portainer_certificado
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 5

  portainer:
    image: portainer/portainer-ce:2.16.1
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    privileged: true
    userns_mode: host
    volumes:
      - type: volume
        source: portainer_data
        target: /data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "/docker", "container", "top", "portainer"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 5
    networks:
      - portainer-network

volumes:
  portainer_data:

networks:
  portainer-network:
    name: portainer-network